---
title: "MAT434: Competition Assignment 3"
author: "Dr. Gilbert"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: cerulean
---

```{r global-options, include=FALSE}
library(tidyverse)
library(kableExtra)
```

Complete the following:

1. Open RStudio and use `File -> Recent Projects` to select and open the R Project which is managing your GitHub repository.

2. Use `File -> Open File...` and navigate to the location of your R Markdown notebook from Competition Assignment 2. Open it.

3. Run all of the code in your existing notebook. 

4. Add a new section to your notebook called *Model Construction and Interpretation*. You'll start working on this section by discussing and building KNN and decision tree classifiers to predict `priceRange` for properties. You should use cross-validation for hyperparameter tuning and performance estimation.

    + Much like your EDA, this section of your analytics report should include a mixture of discussion and code. You'll need to use narrative discussion (text) to help walk your reader through your approach to modeling and the decisions you are making. They should understand what you are doing and why you are doing it even if they are not an expert in statistical modeling (like you are becoming!). 

5. When you are done, use the blue ball of yarn button to knit the notebook into an HTML document. 

6. Use the `Git` tab in the top right pane of RStudio to *Pull, Commit, Push* your new files to your remote repository at GitHub.

Stop by my office if you have any questions or need help.