---
title: "MAT434: Competition Assignment 4"
author: "Dr. Gilbert"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: cerulean
---

```{r global-options, include=FALSE}
library(tidyverse)
library(kableExtra)
```

Complete the following:

1. Open RStudio and use `File -> Recent Projects` to select and open the R Project which is managing your GitHub repository.

2. Use `File -> Open File...` and navigate to the location of your R Markdown notebook from Competition Assignment 2. Open it.

3. Run all of the code in your existing notebook. 

4. You'll be adding to your *Model Construction and Interpretation* section in this assignment. Your focus here will be to tune ensembles (random forest, gradient boosting models, customized model stacks) to try and outperform your existing best-performing KNN or decision tree classifier.

    + Again, make sure you are including ample discussion to justify your modeling choices and to help your reader(s) understand what you are doing. If decision-makers can't follow your analysis then you'll have a really difficult time convincing them that they should utilize your models.

5. When you are done, use the blue ball of yarn button to knit the notebook into an HTML document. 

6. Use the `Git` tab in the top right pane of RStudio to *Pull, Commit, Push* your new files to your remote repository at GitHub.

Stop by my office if you have any questions or need help.