---
title: "MAT434: Competition Assignment 5"
author: "Dr. Gilbert"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: cerulean
---

```{r global-options, include=FALSE}
library(tidyverse)
library(kableExtra)
```

Complete the following:

1. Open RStudio and use `File -> Recent Projects` to select and open the R Project which is managing your GitHub repository.

2. Use `File -> Open File...` and navigate to the location of your R Markdown notebook from Competition Assignment 2. Open it.

Now that you've learned about techniques for extracting signals from text features, its time to revisit the `description` feature in your data set. 

4. Head back to the EDA section of your notebook and apply what you've learned about text analysis to your *training* data. Refer back to our recent notebooks about any functionality you'll want to import or utilize.

5. Once you are satisfied with your EDA, head over to your *Model Construction and Interpretation* section. See if you can improve upon your existing models by extracting text-based features from the `description` feature.

6. Use your new model to make predictions for the properties in `comp.csv`. Submit those predictions to our class Kaggle competition for scoring.

7. When you are done, use the blue ball of yarn button to knit the notebook into an HTML document. 

8. Use the `Git` tab in the top right pane of RStudio to *Pull, Commit, Push* your new files to your remote repository at GitHub.

Stop by my office if you have any questions or need help.