---
title: "MAT434: Homework 2"
author: "Dr. Gilbert"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: cerulean
---

```{r global-options, include=FALSE}
library(tidyverse)
library(kableExtra)
```

You've been working on your initial data wrangling and analysis ([new students](https://agmath.github.io/ClassificationCourse/Day2_TidyAnalyses_newStudents.html), [returning students](https://agmath.github.io/ClassificationCourse/Day2_TidyAnalyses_returningStudents.html), [python users](https://agmath.github.io/ClassificationCourse/Day2_DataWrangling_Python.html)) in an R project that is managing a GitHub Repository. Complete the following:

1. Knit your markdown file to generate the HTML notebook.
2. Use the `Git` tab in the top-right pane of RStudio to *Pull* in changes from your remote repository. The button for pulling in changes is the blue down arrow -- you should already be up to date.
3. Click the checkboxes next to your Rmd and html files and then click the *Commit`* button.
4. Add a commit message in the text box and click the button to *commit* your changes.
5. Click the green up arrow to *push* your changes out to your remote repository on GitHub.
6. Submit a link to your GitHub repository as your submission for HW 2 on BrightSpace.

Stop by my office if you have any questions or need help.